edupedia/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [


    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('epsearch.urls')),
]

epsearch/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from epsearch import views
from epsearch.views import SearchView



urlpatterns = patterns('',
  url(r'^$', TemplateView.as_view(template_name="epsearch/index.html"), name="index"),
  url(r'^search/$', SearchView.as_view(), name="search"),
)

epsearch/models.py
from django.db import models

class Page(models.Model):
    url = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now=True)
    modified_at = models.DateTimeField(auto_now_add=True)




class Sentence(models.Model):
    page = models.ForeignKey(Page)
    body = models.TextField(max_length=1024,null=True,default="")
    comment = models.TextField(null=True,default="")
    created_at = models.DateTimeField(auto_now=True)
    modified_at = models.DateTimeField(auto_now_add=True)

class Term(models.Model):
    sentence = models.ForeignKey(Sentence)
    body = models.CharField(max_length=128,null=True,default="")
    term_class = models.CharField(max_length=30)
    result =  models.TextField(null=True,default="")
    comment = models.TextField(null=True,default="")
    created_at = models.DateTimeField(auto_now=True)
    modified_at = models.DateTimeField(auto_now_add=True)


class DragonHistory(models.Model):
    age = models.IntegerField()
    event = models.TextField(null=True,default="")
    comment = models.TextField(null=True,default="")

epsearch/views.py
#encoding=utf-8
import logging

from django.shortcuts import render
from django.views.generic import TemplateView

from epsearch import docomo_analys
from epsearch.hakipedia import fetch_wiki
from epsearch.keyword_to_image_url import GoogleImageConverter, GoogleMapConverter, GooglePhotoConverter
from epsearch.models import Page, Sentence


L = logging.getLogger(__name__)


class SearchView(TemplateView):
    template_name = "epsearch/search2.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context["page"] = load_page(pagename=request.GET.get("k"),
                                    force=request.GET.get("f"))
        context["sentences"] = context["page"].sentence_set.all()
        return self.render_to_response(context)




CONVERT_MAP = {
       "PSN":GoogleImageConverter,
       "LOC":GoogleMapConverter,
       "ART":GooglePhotoConverter,
       "ORG":GooglePhotoConverter,
       }

def load_page(pagename, limit=5, force=False):
    if not pagename:
        return
    pagename = pagename.strip()
    L.debug( u"[S] load_page: %s" % pagename )
    try:
        if force:
            Page.objects.filter(url=pagename).delete()
        page = Page.objects.get(url=pagename)
    except Page.DoesNotExist:
        page = process_data(pagename, limit)

    return page

def process_data(pagename, limit=5):
    pagename = pagename.strip()
    L.debug( u"[S] process_data: %s" % pagename )
    page = Page()
    page.url = pagename
    page.save()

    body = fetch_wiki(pagename)

    lines = body.split(u"。")
    cnt = 0;
    for line in lines:
        if limit > 0 and cnt > limit:
            L.debug( "limit sentence")
            break
        cnt = cnt + 1
        sen = Sentence()
        sen.page = page
        sen.body = line + u"。"
        sen.save()
        terms = docomo_analys.analysys(sen.body)
        for term in terms:
            term.sentence = sen
            term.save()
            converter = CONVERT_MAP.get(term.term_class)
            if not converter:
                continue
            term.result, term.comment = converter().convert_term(term.body)
            term.save()
    L.debug("[E] process_data")
    return page

epsearch/templates/epsearch/index.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
 <title>Edupedia - Burning CURIOSITY</title>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>



<div class="container" style="margin-top:20%;margin-bottom:30px;">
 <div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h2 class="center-text">Welcome to Edupedia</h2>
  </div>
 </div>
</div>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
	<form action="{% url 'search'%}" class="">
		<div class="form-group">
			<label class="sr-only" for="Email">検索文字列</label>
			<div class="input-group">
				<input name="k" type="text" class="form-control" placeholder="Wikipediaを検索">
				<span class="input-group-btn">
					<input type="submit" class="btn btn-default" value="Go!">
	  			</span>
  			</div>
		</div>
	</form>
  </div><!--col-->
  </div><!--row-->
</div><!--container-->


</body>


epsearch/templates/epsearch/search.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
 <title></title>
</head>
<body>
Search to Edupedia
<ul>
{% for sentence in sentences%}
	<li>{{sentence.body}}</li>
	<ul>
		{% for term in sentence.term_set.all %}
		<li>{{term.term_class}}:{{term.body}} - <img src="{{term.result}}"></li>
		{% endfor %}
	</ul>
{% endfor %}
</ul>
</body>


epsearch/templates/epsearch/search2.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
 <title>Edupedia - Burning CURIOSITY</title>
 {% comment %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
{%endcomment%}
		<link rel="stylesheet" href="{{STATIC_URL}}reveal/css/reveal.css">
		<link rel="stylesheet" href="{{STATIC_URL}}reveal/css/theme/black.css">

		<!-- Theme used for syntax highlighting of code -->
		<link rel="stylesheet" href="{{STATIC_URL}}reveal/lib/css/zenburn.css">
		<style type="text/css">
		 .reveal section{
			background-color: rgba(10, 10, 10, 0.6);
			border-radius: 10px;
			padding: 10px;
		 }
		 .reveal section.stack {
			background-color: rgba(10, 10, 10, 0.6);
			border-radius: 10px;
			padding: 10px;
		 }
		</style>
</head>
<body>
<div class="reveal">
	<div class="slides">
{% for sentence in sentences%}
	<section>{{sentence.body}}
		
	{% for term in sentence.term_set.all %}
	<section data-background="{{term.result}}" data-background-size="contain">
		{{term.term_class}}:{{term.body}} - 
	</section>
	{% endfor %}
		
	</section>
{% endfor %}

	</div><!--slides-->
</div>

<script src="{{STATIC_URL}}reveal/lib/js/head.min.js"></script>
<script src="{{STATIC_URL}}reveal/js/reveal.js"></script>

<script>
	// More info https://github.com/hakimel/reveal.js#configuration
	Reveal.initialize({
		history: true,

		// More info https://github.com/hakimel/reveal.js#dependencies
		dependencies: [
			{ src: '{{STATIC_URL}}reveal/plugin/markdown/marked.js' },
			{ src: '{{STATIC_URL}}reveal/plugin/markdown/markdown.js' },
			{ src: '{{STATIC_URL}}reveal/plugin/notes/notes.js', async: true },
			{ src: '{{STATIC_URL}}reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } }
		]
	});
</script>
</body>
</html>